### ISSUE TITLE
Script not working anymore

### ISSUE THREAD

**Issue by michaeljames728** [fbird17/GM_AddFantasyToMyYahoo#2]
fbird17 Please update your script to work with the new firefox and the new greasemonkey addon. Thanks in advanced .. your awesome for making this in the first place.

**Comment by fbird17** [comment]
Thanks for pointing this out. Looks like Greasemonkey 4 broke compatibility. I have updated the script to work with Greasemonkey 4. Let me know if it doesn't work.  FYI, for other scripts that run into this problem and aren't updated, you can use Tampermonkey instead of Greasemonkey.

**Comment by michaeljames728** [comment]
No it still doesn't work fbird17.

**Comment by fbird17** [comment]
Hmm. Are you sure you are using the new version - version 0.2.0? If so, would you mind turning on the browser console and sending me the debug log?

**Comment by michaeljames728** [comment]
I click the (raw) for version 0.2.0 and it doesn't download into greasemonkey 4.0. Nothing happens and when i check the greasemonkey icon at top right it says No user scripts installed. btw i don't know how to turn on the browser console and send you a debug log either  :/

**Comment by michaeljames728** [comment]
Ok i installed tampermonkey and the script works now. Thank you.

**Comment by fbird17** [comment]
Great. If you don't like tampermonkey, I think I figured out the problem. Something about the file on gituserhub is making Firefox think it is a text file. Opening this file from here should work:
https://rawgit.com/fbird17/GM_AddFantasyToMyYahoo/master/GM_AddFantasyToMyYahoo.user.js

**Comment by michaeljames728** [comment]
Yes whatever you did fixed the problem and now greasemonkey installed it. Thanks bro.

**Comment by michaeljames728** [comment]
Hey fbird17, Is there any chance you could update your script again please? It's still mostly working there is just some things that are starting to bug and not show correctly. Thanks in advanced.

**Comment by fbird17** [comment]
It is still working fine for me. Checked it in both Chrome and Firefox. What isn't showing up correctly?

**Comment by michaeljames728** [comment]
The wrong teams are matched together on my fantasy football leagues and the league names and numbers aren't showing anymore. It's probably because I have 8 teams that show and a basketball team that doesn't show so it's too much for the addon.
